home/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from home.views import HomeView

 
app_name = "home"
urlpatterns = [
     path('',HomeView.as_view(), name='home'),
     url(r'^post/(?P<pk>[0-9]+)/$', views.Post_detail, name='Post_detail'),
     url(r'^cmnt/(?P<pk>[0-9]+)/$', views.cmnt, name='cmnt'),
     url(r'^like/$', views.like_post, name='like_post'),
     # path('post/(?P<pk>/d+)', views.post_detail, name = 'post_detail' ),
     # path('cmnt/',views.cmnt, name='cmnt'),
     ]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial.views import index
from django.conf import settings
from django.conf.urls import url
from myproject.views import login_redirect,land
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',index), 
    path('accounts/', include('accounts.urls' , namespace='accounts') ),
    # path('',login_redirect , name = 'login_redirect'),
    path('home/', include('home.urls' , namespace='home') ),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('',land , name = 'land'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

reviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'reviews'
urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
]

reviews/models.py
from django.db import models
from accounts.models import User
# import numpy as np


class Wine(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to = 'product_image', null=True, blank=True)
    
    # def average_rating(self):
    #     all_ratings = map(lambda x: x.rating, self.review_set.all())
    #     return np.mean(all_ratings)
        
    def __unicode__(self):
        return self.name
    def __str__(self):
    	return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    user = models.ForeignKey(User, on_delete = 'models.CASCADE')
    wine = models.ForeignKey(Wine, on_delete = 'models.CASCADE')
    pub_date = models.DateTimeField(auto_now_add=True)
    # user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

    def __unicode__(self):
        return self.wine.name
    def __str__(self):
        return self.wine.name

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review
from django import forms

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment',]
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15})
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Review, Wine 
from .forms import ReviewForm
import datetime


def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    print(latest_review_list)
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)
 
 
def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list':wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})


def add_review(request, wine_id):
    if request.method == 'POST':
        wine = get_object_or_404(Wine, pk=wine_id)
        form = ReviewForm(request.POST)
        print('1')
        if form.is_valid():
            print('2')
            comment = form.save(commit = False)
            comment.user = request.user 
            comment.wine = wine 
                # ***this where i am unable to assign my comment to the respective post***
            #comment.post_id =pk
            comment.save()
            #text1 = form1.cleaned_data['comment']
            #form1 = CommentForm()
            form = ReviewForm()
            return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))
            # args ={
            #         'post':post , 'form1':form1,'comment':comment,
            #         'pk':pk, 'text1': text1,
                     
            #     }
            # return render(request,'home/post_detail.html',args)

        print('3')
        args = {'form': form, }
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))    





    # wine = get_object_or_404(Wine, pk=wine_id)
    # form = ReviewForm(request.POST)
    # user_name = request.user
    # print(user_name)
    # if form.is_valid():
    #     rating = form.cleaned_data['rating']
    #     comment = form.cleaned_data['comment']
    #     # user_name = form.cleaned_data['user_name']
    #     user_name = request.user
    #     print(user_name)
    #     if comment:
    #         print(comment)
    #     else:
    #         print('1')
    #     print(rating)
    #     review = Review()
    #     review.wine = wine
    #     review.user_name = user_name
    #     review.rating = rating
    #     review.comment = comment
    #     review.pub_date = datetime.datetime.now()
    #     review.save()
    #     # Always return an HttpResponseRedirect after successfully dealing
    #     # with POST data. This prevents data from being posted twice if a
    #     # user hits the Back button.
    #     return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))

    # return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})




    # def add_review(request, wine_id):
    # wine = get_object_or_404(Wine, pk=wine_id)
    # form = ReviewForm(request.POST)
    # user_name = request.user
    # print(user_name)
    # if form.is_valid():
    #     rating = form.cleaned_data['rating']
    #     comment = form.cleaned_data['comment']
    #     # user_name = form.cleaned_data['user_name']
    #     user_name = request.user
    #     print(user_name)
    #     if comment:
    #         print(comment)
    #     else:
    #         print('1')
    #     print(rating)
    #     review = Review()
    #     review.wine = wine
    #     review.user_name = user_name
    #     review.rating = rating
    #     review.comment = comment
    #     review.pub_date = datetime.datetime.now()
    #     review.save()
    #     # Always return an HttpResponseRedirect after successfully dealing
    #     # with POST data. This prevents data from being posted twice if a
    #     # user hits the Back button.
    #     return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))

    # return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}


{% block body %}
<h2>Reviews</h2>
{% if review %}
<div>

    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>

</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
<h2>Latest reviews</h2>

{% block body %}
<h2>Latest reviews</h2>
{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block body %}
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div class="row">
    {% for review in wine.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <h2><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h2>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user}}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="form-group row">
      <form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
        {% csrf_token %}
        
        {{ form.comment }}
        {{ form.rating }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>


{% endblock %}

reviews/templates/reviews/wine_list.html
{% extends 'base.html' %}
{% block body %}
<h2>Wine list</h2>

{% if wine_list %}
<div>
	{% for wine in wine_list %}
    <div>
        <h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }} 
        <img src="{{ wine.photo.url }}" width="80" height="80">
        </a></h4>
    </div>
    {% endfor %}

</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}