accounts/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from django.contrib.auth.views import (
 login , logout, password_reset,
  password_reset_done , password_reset_confirm,
  password_reset_complete
  )
from django.conf import settings
app_name = "accounts"  

urlpatterns = [
     # path('',views.home,name='home'),
     # path('login/', login ,  {'template_name': 'accounts/login.html' } , name='login' ),
     path('login1/', views.landing_page , name='login1' ),
     path('logout/', logout ,  {'template_name': 'accounts/logout.html' },name='logout'),
     path('register/', views.register , name= 'register'),
     path('register1/', views.register1 , name= 'register1'),
     url(r'^profile/(?P<username>\w+)/?$', views.view_profile, name='profile'),
     #path('profile/', views.view_profile , name= 'profile'),
     url(r'^edit/$',views.edit_profile, name='edit_profile'),
     path('search/',views.search, name='search'),
     path('change-password/',views.change_password, name='change_password'),
     path('reset-password/', password_reset,{'template_name':
                 'accounts/reset_password.html' , 'post_reset_redirect':'accounts:password_reset_done',
                 'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),

     path('reset-password/done/', password_reset_done, {'template_name':
                 'accounts/reset_password_done.html'} , name='password_reset_done'),
 
     path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/',password_reset_confirm,{'template_name':
                 'accounts/reset_password_confirm.html',
                   'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

     path('reset-password/complete', password_reset_complete,
                    {'template_name':
                 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
     path('model/',views.model, name='model'),
     path('model_view/',views.view_model, name='view_model'),
     path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
]

home/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from home.views import HomeView

 
app_name = "home"
urlpatterns = [
     path('',HomeView.as_view(), name='home'),
     url(r'^post/(?P<pk>[0-9]+)/$', views.Post_detail, name='Post_detail'),
     url(r'^cmnt/(?P<pk>[0-9]+)/$', views.cmnt, name='cmnt'),
     url(r'^like/$', views.like_post, name='like_post'),
     # path('post/(?P<pk>/d+)', views.post_detail, name = 'post_detail' ),
     # path('cmnt/',views.cmnt, name='cmnt'),
     ]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial.views import index
from django.conf import settings
from django.conf.urls import url
from myproject.views import login_redirect,land
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',index), 
    path('accounts/', include('accounts.urls' , namespace='accounts') ),
    # path('',login_redirect , name = 'login_redirect'),
    path('home/', include('home.urls' , namespace='home') ),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('',land , name = 'land'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

reviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'reviews'
urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    post = models.CharField(max_length=500)
    image = models.ImageField(upload_to = 'profile_image')
    user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
    likes = models.ManyToManyField(User , related_name='likes', blank = True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    restrict_comment =  models.BooleanField(default=False)

    def __str__(self):
        return self.post

    def total_likes(self):
        return self.likes.count()
 
    def get_absolute_url(self,request):
        # id = request.POST.get('post_id')
        return reverse('home:Post_detail',kwargs={'pk':post_id})


class ImagePost(models.Model):
	user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
	post = models.CharField(max_length= 500)
	image =  models.FileField(upload_to = 'profile_image')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete = 'models.CASCADE')
    post = models.ForeignKey(Post, null = True, on_delete = 'models.CASCADE')
    reply = models.ForeignKey('self',null=True,related_name= 'replies',on_delete='models.CASCADE')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

 
    def __str__(self):
        return self.comment
        

home/forms.py
from django import forms
from home.models import Post, ImagePost,Comment


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))
    image = forms.ImageField()

    class Meta:
        model = Post
        fields = ('post','image',)

class Home(forms.ModelForm):
	post = forms.CharField()
	image = forms.FileField()
	

	class Meta:
		model = ImagePost
		fields = ('post' , 'image' ,)

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.models import User
from home.forms import HomeForm,Home,CommentForm
from home.models import Post ,ImagePost,Comment
from django.db.models import Q
from django.urls import reverse 
from django.http import HttpResponse, JsonResponse, Http404
from django.template.loader import render_to_string

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        post_list = None
        form = HomeForm(self.request.GET or None)
        form1 = CommentForm(self.request.GET or None)
        posts = Post.objects.filter(user = request.user).order_by('-created')
        comments = Comment.objects.all()
        users = User.objects.exclude(id=request.user.id)
        query = request.GET.get('q')    
        if query:
                posts = Post.objects.filter(
                        Q(post__icontains=query)
                        )
                context = {
                        'posts': posts, }   
                print(posts)
        args = {
            'form': form, 'posts': posts, 'users': users, 'form1':form1,
            'comments':comments,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form1 = CommentForm()
        text = ''
        # if request.method == 'POST':
        #     form = HomeForm(request.POST,request.FILES)
        #     if form.is_valid():

        #         post = form.save(commit=False)
        #         post.user = request.user
        #         post.save()
        #         text = form.cleaned_data['post']
        #         form = HomeForm()
        #         form1 = CommentForm()
        #         return redirect('home:home')
        if request.method=='POST' and 'btn1' in request.POST:
            post_list = Post.published.all()
            query = request.GET.get('q')
            if query:
                post_list = Post.objects.filter(
                        Q(post__icontains=query)
                        )
                context = {
                        'posts_list': posts_list,
                                }
                print(posts_list)
                return redirect('home:home')
        if request.method=='POST' and 'btn' in request.POST:
            form = HomeForm(request.POST,request.FILES)
            if form.is_valid():

                post = form.save(commit=False)
                post.user = request.user
                post.save()
                text = form.cleaned_data['post']
                form = HomeForm()
                form1 = CommentForm()
        return redirect('home:home')


# def post_list(request):
#     post_list=None
#     query = request.GET.get('q')
#     if query:
#         post_list = Post.published.filter(
#                 Q(post__icontains=query)|
#                 Q(author__username=query)
#                 )  
#     context = {
#         'post_list': post_list,

#     }
        # if request.method == 'POST':
        #     form1 = CommentForm(request.POST,Post.id)
        #     text1 = ''
        #     post = ''
        #     if form1.is_valid():
        #         comment = form1.save(commit = False)
        #         comment.user = request.user  
        #         # ***this where i am unable to assign my comment to the respective post***
        #         # comment.post_id =post.id
        #         comment.save()
        #         text1 = form1.cleaned_data['comment']
        #         form1 = CommentForm()
        #         form = HomeForm()
        #         return redirect('home:home')


        # args = {'form': form, 'text': text ,'text1': text1 , 'form1':form1}
        # return render(request, self.template_name, args)


def Post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=pk,reply = None).order_by('-pk')
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    form1 = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        reply_id = None
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('home/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'home/post_detail.html', context)


# class LikeView(TemplateView):
#     template_name = 'home/post_detail.html'

#     def post(self,request):
#         post = get_object_or_404(Post,id = request.POST.get('post_id'))
#         post.likes.add(request.user)
#         return HttpResponseRedirect(Post.get_absolute_url(self))

#     def get_absolute_url(self,request):
#         id = request.POST.get('post_id')
#         return reverse('home:Post_detail',kwargs={'pk':id})


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else: 
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),

    }
    if request.is_ajax():
        html = render_to_string('home/like_section.html', context, request=request)
        return JsonResponse({'form': html})
    
    



def cmnt(request,pk):
    if request.method == 'POST':
        form = HomeForm()
        form1 = CommentForm(request.POST or None)
        text1 = '' 
        post = ''
        if form1.is_valid():
            comment = form1.save(commit = False)
            comment.user = request.user  
                # ***this where i am unable to assign my comment to the respective post***
            comment.post_id =pk
            comment.save()
            text1 = form1.cleaned_data['comment']
            form1 = CommentForm()
            form = HomeForm()
            return HttpResponseRedirect(get_absolute_url())
            # args ={
            #         'post':post , 'form1':form1,'comment':comment,
            #         'pk':pk, 'text1': text1,
                     
            #     }
            # return render(request,'home/post_detail.html',args)


        args = {'form': form, 'text1': text1 , 'form1':form1}
        return render(request, 'home/home.html', args)










# def like_post(request):
#         post = get_object_or_404(Post,id=request.POST.get("post_id"))
#         is_liked = False
#         if post.likes.filter(id=request.user.id).exists():
#             post.likes.remove(request.user)
#             is_liked = False
#         else:
#             is_liked = True
#             post.likes.add(request.user.id)
#         return HttpResponseRedirect(post.get_absolute_url())
    





















# class HomeView(TemplateView):
#     template_name = 'home/home.html'

#     def get(self, request):
#         form = HomeForm()
#         form1 = CommentForm()
#         posts = Post.objects.filter(user = request.user).order_by('-created')
#         comments = Comment.objects.all()
#         users = User.objects.exclude(id=request.user.id)
#         args = {
#             'form': form, 'posts': posts, 'users': users, 'form1':form1,
#             'comments':comments,
#         }
#         return render(request, self.template_name, args)

#     def post(self, request):
#         form1 = CommentForm()
#         text = ''
#         if request.method == 'POST':
#             form = HomeForm(request.POST,request.FILES)
#             if form.is_valid():
                
#                 post = form.save(commit=False)
#                 post.user = request.user
#                 post.save()
#                 text = form.cleaned_data['post']
#                 form = HomeForm()
#                 form1 = CommentForm()
#                 return redirect('home:home')
                
#         def cmnt(self , request):
#             text = ''
#             form1 = CommentForm()
#             if request.method == 'POST':
#                 form1 = CommentForm(request.POST,post.id)
#                 if form.is_valid():
#                     comment = form.save(commit = False)
#                     comment.user = request.user
#                     comment.post = request.post
#                     comment.save()
#                     text = form.cleaned_data['comment']
#                     form1 = CommentForm()
#                     form = HomeForm()
#                     return redirect('home:home')

#                 args = {'form': form, 'text': text , 'form1':form1}
#                 return render(request, self.template_name, args)


  



    

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  {% block head %}
  <title>base</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" >
  </head>
  <body>
    <br>
  {% if user.is_authenticated %}
   <nav class="navbar navbar-default bg-light navbar-light" >
   <a class="navbar-brand" href="{% url 'home:home' %}">All About Hairdressers</a>

   <a class="navbar-brand left" href="{% url 'home:home' %}">HOME</a>
   <a class="navbar-brand left" href="{% url 'accounts:logout' %}">logout</a>
   <a class="navbar-brand left" href="{% url 'accounts:change_password'%}">change password</a>
   <a class="navbar-brand left" href="{% url 'accounts:profile' user.username  %}">profile</a>
   <a class="navbar-brand left" href="{% url 'accounts:edit_profile'  %}">edit_profile</a>
   <a class="navbar-brand left" href="{% url 'reviews:wine_list'  %}">review</a>
     <ul class="nav navbar-nav navbar-right">
      
    </ul>
   </nav>
   {% else %}
   <nav class="navbar navbar-default bg-light navbar-light">
   <a class="navbar-brand" href="#">All About Hairdressers</a>

    </form>
     <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'accounts:search' %}">SEARCH</a></li>
      <li><a href="{% url 'accounts:register' %}">Register</a></li>
      <li><a class="navbar-brand" href="{% url 'accounts:login1' %}">login</a></li>
      <li><a class="navbar-brand left" href="{% url 'accounts:reset_password' %}">reset password</a></li>
      <a class="navbar-brand left" href="{% url 'reviews:wine_list'  %}">review</a>
    </ul>
   </nav>
   {% endif %}
     <div class="container-fluid">
      {% block body %}
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">

        $('.reply-btn').click(function() {
          $(this).parent().parent().next('.replied-comments').fadeToggle()
        });

        $(document).on('click', '#like', function(event){
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "home:like_post" %}',
            data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
              $('#like-section').html(response['form'])
              console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
        });

        $(document).on('submit', '.comment-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });


        $(document).on('submit', '.reply-form', function(event){
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
              $('.main-comment-section').html(response['form']);
              $('textarea').val('');
              $('.reply-btn').click(function() {
                $(this).parent().parent().next('.replied-comments').fadeToggle();
                $('textarea').val('');
              });
            },
            error: function(rs, e) {
              console.log(rs.responseText);
            },
          });
        });
    </script>
  </body>
</html>