home/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from home.views import HomeView

 
app_name = "home"
urlpatterns = [
     path('',HomeView.as_view(), name='home'),
     url(r'^post/(?P<pk>[0-9]+)/$', views.Post_detail, name='Post_detail'),
     url(r'^cmnt/(?P<pk>[0-9]+)/$', views.cmnt, name='cmnt'),
     url(r'^like/$', views.like_post, name='like_post'),
     # path('post/(?P<pk>/d+)', views.post_detail, name = 'post_detail' ),
     # path('cmnt/',views.cmnt, name='cmnt'),
     ]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial.views import index
from django.conf import settings
from django.conf.urls import url
from myproject.views import login_redirect,land
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',index), 
    path('accounts/', include('accounts.urls' , namespace='accounts') ),
    # path('',login_redirect , name = 'login_redirect'),
    path('home/', include('home.urls' , namespace='home') ),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('',land , name = 'land'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    post = models.CharField(max_length=500)
    image = models.ImageField(upload_to = 'profile_image')
    user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
    likes = models.ManyToManyField(User , related_name='likes', blank = True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    restrict_comment =  models.BooleanField(default=False)

    def __str__(self):
        return self.post

    def total_likes(self):
        return self.likes.count()
 
    def get_absolute_url(self,request):
        # id = request.POST.get('post_id')
        return reverse('home:Post_detail',kwargs={'pk':post_id})


class ImagePost(models.Model):
	user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
	post = models.CharField(max_length= 500)
	image =  models.FileField(upload_to = 'profile_image')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete = 'models.CASCADE')
    post = models.ForeignKey(Post, null = True, on_delete = 'models.CASCADE')
    reply = models.ForeignKey('self',null=True,related_name= 'replies',on_delete='models.CASCADE')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

 
    def __str__(self):
        return self.comment
        

home/forms.py
from django import forms
from home.models import Post, ImagePost,Comment


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))
    image = forms.ImageField()

    class Meta:
        model = Post
        fields = ('post','image',)

class Home(forms.ModelForm):
	post = forms.CharField()
	image = forms.FileField()
	

	class Meta:
		model = ImagePost
		fields = ('post' , 'image' ,)

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.models import User
from home.forms import HomeForm,Home,CommentForm
from home.models import Post ,ImagePost,Comment
from django.db.models import Q
from django.urls import reverse 
from django.http import HttpResponse, JsonResponse, Http404
from django.template.loader import render_to_string

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        post_list = None
        form = HomeForm(self.request.GET or None)
        form1 = CommentForm(self.request.GET or None)
        posts = Post.objects.filter(user = request.user).order_by('-created')
        comments = Comment.objects.all()
        users = User.objects.exclude(id=request.user.id)
        query = request.GET.get('q')    
        if query:
                posts = Post.objects.filter(
                        Q(post__icontains=query)
                        )
                context = {
                        'posts': posts, }   
                print(posts)
        args = {
            'form': form, 'posts': posts, 'users': users, 'form1':form1,
            'comments':comments,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form1 = CommentForm()
        text = ''
        # if request.method == 'POST':
        #     form = HomeForm(request.POST,request.FILES)
        #     if form.is_valid():

        #         post = form.save(commit=False)
        #         post.user = request.user
        #         post.save()
        #         text = form.cleaned_data['post']
        #         form = HomeForm()
        #         form1 = CommentForm()
        #         return redirect('home:home')
        if request.method=='POST' and 'btn1' in request.POST:
            post_list = Post.published.all()
            query = request.GET.get('q')
            if query:
                post_list = Post.objects.filter(
                        Q(post__icontains=query)
                        )
                context = {
                        'posts_list': posts_list,
                                }
                print(posts_list)
                return redirect('home:home')
        if request.method=='POST' and 'btn' in request.POST:
            form = HomeForm(request.POST,request.FILES)
            if form.is_valid():

                post = form.save(commit=False)
                post.user = request.user
                post.save()
                text = form.cleaned_data['post']
                form = HomeForm()
                form1 = CommentForm()
        return redirect('home:home')


# def post_list(request):
#     post_list=None
#     query = request.GET.get('q')
#     if query:
#         post_list = Post.published.filter(
#                 Q(post__icontains=query)|
#                 Q(author__username=query)
#                 )  
#     context = {
#         'post_list': post_list,

#     }
        # if request.method == 'POST':
        #     form1 = CommentForm(request.POST,Post.id)
        #     text1 = ''
        #     post = ''
        #     if form1.is_valid():
        #         comment = form1.save(commit = False)
        #         comment.user = request.user  
        #         # ***this where i am unable to assign my comment to the respective post***
        #         # comment.post_id =post.id
        #         comment.save()
        #         text1 = form1.cleaned_data['comment']
        #         form1 = CommentForm()
        #         form = HomeForm()
        #         return redirect('home:home')


        # args = {'form': form, 'text': text ,'text1': text1 , 'form1':form1}
        # return render(request, self.template_name, args)


def Post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=pk,reply = None).order_by('-pk')
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    form1 = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        reply_id = None
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('home/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'home/post_detail.html', context)


# class LikeView(TemplateView):
#     template_name = 'home/post_detail.html'

#     def post(self,request):
#         post = get_object_or_404(Post,id = request.POST.get('post_id'))
#         post.likes.add(request.user)
#         return HttpResponseRedirect(Post.get_absolute_url(self))

#     def get_absolute_url(self,request):
#         id = request.POST.get('post_id')
#         return reverse('home:Post_detail',kwargs={'pk':id})


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else: 
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),

    }
    if request.is_ajax():
        html = render_to_string('home/like_section.html', context, request=request)
        return JsonResponse({'form': html})
    
    



def cmnt(request,pk):
    if request.method == 'POST':
        form = HomeForm()
        form1 = CommentForm(request.POST or None)
        text1 = '' 
        post = ''
        if form1.is_valid():
            comment = form1.save(commit = False)
            comment.user = request.user  
                # ***this where i am unable to assign my comment to the respective post***
            comment.post_id =pk
            comment.save()
            text1 = form1.cleaned_data['comment']
            form1 = CommentForm()
            form = HomeForm()
            return HttpResponseRedirect(get_absolute_url())
            # args ={
            #         'post':post , 'form1':form1,'comment':comment,
            #         'pk':pk, 'text1': text1,
                     
            #     }
            # return render(request,'home/post_detail.html',args)


        args = {'form': form, 'text1': text1 , 'form1':form1}
        return render(request, 'home/home.html', args)










# def like_post(request):
#         post = get_object_or_404(Post,id=request.POST.get("post_id"))
#         is_liked = False
#         if post.likes.filter(id=request.user.id).exists():
#             post.likes.remove(request.user)
#             is_liked = False
#         else:
#             is_liked = True
#             post.likes.add(request.user.id)
#         return HttpResponseRedirect(post.get_absolute_url())
    





















# class HomeView(TemplateView):
#     template_name = 'home/home.html'

#     def get(self, request):
#         form = HomeForm()
#         form1 = CommentForm()
#         posts = Post.objects.filter(user = request.user).order_by('-created')
#         comments = Comment.objects.all()
#         users = User.objects.exclude(id=request.user.id)
#         args = {
#             'form': form, 'posts': posts, 'users': users, 'form1':form1,
#             'comments':comments,
#         }
#         return render(request, self.template_name, args)

#     def post(self, request):
#         form1 = CommentForm()
#         text = ''
#         if request.method == 'POST':
#             form = HomeForm(request.POST,request.FILES)
#             if form.is_valid():
                
#                 post = form.save(commit=False)
#                 post.user = request.user
#                 post.save()
#                 text = form.cleaned_data['post']
#                 form = HomeForm()
#                 form1 = CommentForm()
#                 return redirect('home:home')
                
#         def cmnt(self , request):
#             text = ''
#             form1 = CommentForm()
#             if request.method == 'POST':
#                 form1 = CommentForm(request.POST,post.id)
#                 if form.is_valid():
#                     comment = form.save(commit = False)
#                     comment.user = request.user
#                     comment.post = request.post
#                     comment.save()
#                     text = form.cleaned_data['comment']
#                     form1 = CommentForm()
#                     form = HomeForm()
#                     return redirect('home:home')

#                 args = {'form': form, 'text': text , 'form1':form1}
#                 return render(request, self.template_name, args)


  



    

home/templates/home/comments.html
<div class="container-fluid mt-2">
  <div class="form-group row">
    <form method="post" class="comment-form" action=".">
      {% csrf_token %}
      {{ comment_form.as_p }}
      {% if request.user.is_authenticated %}
        <input type="submit" value="Submit" class="btn btn-outline-success">
      {% else %}
        <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
      {% endif %}
    </form>
  </div>
</div>

{{ comments.count }} Comment{{ comments|pluralize }}
{% for comment in comments %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{ comment.content }}</small></p>
    <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
      <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
    </footer>
  </blockquote>

  <div class="replied-comments container mt-2" style="display:none;">
    {% for reply in comment.replies.all %}
    <blockquote class="blockquote">
      <p class="mb-0"><small>{{ reply.content }}</small></p>
      <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
    </footer>
    </blockquote>
    {% endfor %}
    <div class="form-group row">
      <form method="post" class="reply-form" action=".">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>
  </div> 
{% endfor %}

home/templates/home/home.html
{% extends 'base.html' %}
{%  load static %}

{% block body %} 
    <form enctype="multipart/form-data" class="form-inline my-2 my-lg-0" action=".">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q'>
      <button class="btn btn-outline-success my-2 my-sm-0" name="btn1" type="submit">Search</button>
    </form>
<div class="container">
    <div class="col-md-8">
        <h2>Home</h2>
        <form  method="POST" enctype="multipart/form-data" type = 'file'>
            {% csrf_token %}
            {{ form.post }}
            {{ form.image }}
            <br>
            <button name="btn" type="submit">Submit</button>
        </form>
        {%if post_list %}
        <h1>QUERY</h1>
        {% for q in post_list %}
        <a href="{% url 'home:Post_detail' pk=post.id %}">{{q.id}}.{{ q.post }}
         <br>
            <img src="{{ q.image.url }}" width="240" height="auto">
            <p>Posted by {{ q.user.get_full_name }} on {{ q.created }}</p>
                  {{comments.count}} comment{{comments|pluralize}}<br>
              {% for comment in post.comment_set.all %}

                <small><b>{{ comment.comment }}</b></small>
                <p>commented by {{ comment.user.get_full_name }} on {{ comment.created }}</p>            
           {% endfor %}
        {%endfor%}
        
        {%else%}
        <h2>{{ text }}</h2>
        {% for post in posts %}
           <a href="{% url 'home:Post_detail' pk=post.id %}"> <h1>{{post.id}}.{{ post.post }}</h1></a>
            <br>
            <img src="{{ post.image.url }}" width = 240 >
            <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
        <!-- <form action="{% url 'home:cmnt' pk=post.id %}" method="POST" enctype="multipart/form-data" type = 'file'>
            {% csrf_token %}
            {{ form1.content }}
            <br>
            <button type="submit">Submit</button>
        </form> -->
                {{comments.count}} comment{{comments|pluralize}}<br>
              {% for comment in post.comment_set.all %}

                <small><b>{{ comment.comment }}</b></small>
                <p>commented by {{ comment.user.get_full_name }} on {{ comment.created }}</p>            
           {% endfor %}
        {% endfor %}

    </div>
    {%endif%}
    
</div>
{% endblock %}

home/templates/home/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'home:like_post' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
  {% endif %}
</form>
{% endif %}

home/templates/home/post_detail.html
{% extends 'base.html' %}
{%  load static %}

{% block body %} 
<div class="container">
    <div class="col-md-8">
            <a href="{ % url 'home:Post_detail' pk=post.id %}"> <h1>{{post.id}}.{{ post.post }}</h1></a>
            <br>
            <img src="{{ post.image.url }}" width = 240 >
            <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>      
    </div>
<div id="like-section">
  {% include 'home/like_section.html' %}
</div>
{% if not post.restrict_comment %}
  <div class="main-comment-section">
    {% include 'home/comments.html' %}
  </div>
{% endif %}

    
</div>
{% endblock %}