accounts/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from django.contrib.auth.views import (
 login , logout, password_reset,
  password_reset_done , password_reset_confirm,
  password_reset_complete
  )
from django.conf import settings
app_name = "accounts"  

urlpatterns = [
     # path('',views.home,name='home'),
     # path('login/', login ,  {'template_name': 'accounts/login.html' } , name='login' ),
     path('login1/', views.landing_page , name='login1' ),
     path('logout/', logout ,  {'template_name': 'accounts/logout.html' },name='logout'),
     path('register/', views.register , name= 'register'),
     path('register1/', views.register1 , name= 'register1'),
     url(r'^profile/(?P<username>\w+)/?$', views.view_profile, name='profile'),
     #path('profile/', views.view_profile , name= 'profile'),
     url(r'^edit/$',views.edit_profile, name='edit_profile'),
     path('search/',views.search, name='search'),
     path('change-password/',views.change_password, name='change_password'),
     path('reset-password/', password_reset,{'template_name':
                 'accounts/reset_password.html' , 'post_reset_redirect':'accounts:password_reset_done',
                 'email_template_name':'accounts/reset_password_email.html'}, name='reset_password'),

     path('reset-password/done/', password_reset_done, {'template_name':
                 'accounts/reset_password_done.html'} , name='password_reset_done'),
 
     path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/',password_reset_confirm,{'template_name':
                 'accounts/reset_password_confirm.html',
                   'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

     path('reset-password/complete', password_reset_complete,
                    {'template_name':
                 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
     path('model/',views.model, name='model'),
     path('model_view/',views.view_model, name='view_model'),
     path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
]

home/urls.py
from django.conf.urls import url 
from django.urls import path
from .import views
from home.views import HomeView

 
app_name = "home"
urlpatterns = [
     path('',HomeView.as_view(), name='home'),
     url(r'^post/(?P<pk>[0-9]+)/$', views.Post_detail, name='Post_detail'),
     url(r'^cmnt/(?P<pk>[0-9]+)/$', views.cmnt, name='cmnt'),
     url(r'^like/$', views.like_post, name='like_post'),
     # path('post/(?P<pk>/d+)', views.post_detail, name = 'post_detail' ),
     # path('cmnt/',views.cmnt, name='cmnt'),
     ]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial.views import index
from django.conf import settings
from django.conf.urls import url
from myproject.views import login_redirect,land
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',index), 
    path('accounts/', include('accounts.urls' , namespace='accounts') ),
    # path('',login_redirect , name = 'login_redirect'),
    path('home/', include('home.urls' , namespace='home') ),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('',land , name = 'land'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

accounts/models.py
from django.db import models
from django.db.models.signals import post_save	
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser
# Create your models here.

# class Username(models.Model):
# 	user = models.ForeignKey(User, on_delete=models.CASCADE)
# 	# username = models.CharField(label='Enter Username', min_length=4, max_length=150)
# 	email = models.EmailField(label='Enter email')
# 	password1 = models.CharField(label='Enter password', widget=forms.PasswordInput)
# 	password2 = models.CharField(label='Confirm password', widget=forms.PasswordInput)
# 	radio = models.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
 


class UserProfileManager(models.Manager):
	"""docstring for UserProfileManager"""
	def get_queryset(self):
		super(UserProfileManager, self).get_queryset().filter(city = 'london')
		

class UserProfile(AbstractBaseUser):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	description = models.CharField(max_length=100,default='')
	city = models.CharField(max_length=100,default='')
	website = models.URLField(default='')
	phone = models.IntegerField(default=0)
	image = models.ImageField(upload_to = 'profile_img',blank= True)
    
	USERNAME_FIELD = 'user'

	def __str__(self):
		return self.user.username

	def __unicode__(self):
		return self.user

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile , sender = User)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to = 'image', null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)

class Product(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
    	return self.name

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    post = models.CharField(max_length=500)
    image = models.ImageField(upload_to = 'profile_image')
    user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
    likes = models.ManyToManyField(User , related_name='likes', blank = True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    restrict_comment =  models.BooleanField(default=False)

    def __str__(self):
        return self.post

    def total_likes(self):
        return self.likes.count()
 
    def get_absolute_url(self,request):
        # id = request.POST.get('post_id')
        return reverse('home:Post_detail',kwargs={'pk':post_id})


class ImagePost(models.Model):
	user = models.ForeignKey(User ,on_delete = 'models.CASCADE')
	post = models.CharField(max_length= 500)
	image =  models.FileField(upload_to = 'profile_image')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete = 'models.CASCADE')
    post = models.ForeignKey(Post, null = True, on_delete = 'models.CASCADE')
    reply = models.ForeignKey('self',null=True,related_name= 'replies',on_delete='models.CASCADE')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

 
    def __str__(self):
        return self.comment
        

tutorial/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from home.models import Post, ImagePost,Comment


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))
    image = forms.ImageField()

    class Meta:
        model = Post
        fields = ('post','image',)

class Home(forms.ModelForm):
	post = forms.CharField()
	image = forms.FileField()
	

	class Meta:
		model = ImagePost
		fields = ('post' , 'image' ,)

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render , redirect ,render_to_response
from django.http import Http404,HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views.generic import TemplateView
from accounts.forms import RegistrationForm, EditProfileForm,ProfileEditForm,UserEditForm
                            # modelform ,CustomUserCreationForm,SignUpForm,UsernameForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from accounts.models import Profile, UserProfile
                                    # ,Username
from django.contrib.auth import login, authenticate
from django.shortcuts import get_object_or_404
from .import forms
from django.db.models import Q
from home.models import Post 

from django.template import RequestContext
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from django.contrib import messages
# Create your views here.

def signup(request,radio):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home:home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/reg_form.html', {'form': form})



 




# def register(request):
#   if request.method == 'POST':
#       form = RegistrationForm(request.POST)
#       if form.is_valid():
#           form.save()
#           return redirect(reverse('accounts:login'))
#   else:
#       form = RegistrationForm()

#   args = {'form':form}
#   return render(request, 'accounts/reg_form.html',args)

# def view_profile(request, pk=None):
#     if pk:
#         print(pk)
#         print('1')
#         user = User.objects.get(pk=pk)
#     else:
#         user = request.user
#         print('2')
#     args = {'user': user}
#     return render(request, 'accounts/profile.html', args)
# @login_required
# def view_profile(request, username):
#     if username:
#         #print(pk)
#         print('1')
#         user = User.objects.get(username=username)
#     else:
#         print('2')
#         user = request.user
#     args = {'user': user}
#     return render(request, 'accounts/profile.html', args)


# @login_required
# def edit_profile(request, username):
#     if username:
#         if request.method == 'POST':
#             #user_form = EditProfileForm(data=request.POST or None, instance=request.user)
#             profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.userprofile, files=request.FILES)
#             if profile_form.is_valid():
#                 print(profile_form)
#                 #user_form.save()
#                 profile_form.save()
#                 return HttpResponseRedirect(reverse("accounts:edit_profile"))
#         else:
#             #user_form = EditProfileForm(instance=request.user)
#             profile_form = ProfileEditForm(instance=request.user.userprofile)
#     else:
#         #user_form = EditProfileForm(instance=request.user)
#         profile_form = ProfileEditForm(instance=request.user.userprofile)

#     context = {
#         #'user_form': user_form,
#         'profile_form': profile_form,
#     }
#     return render(request, 'accounts/edit_profile.html', context)
@login_required(login_url='/accounts/login/')
def view_profile(request, username=None):
    if username:
        #print(pk)
        print(username)
        user = User.objects.get(username=username)
        #user = get_object_or_404(User, username=username)
    else:
        print('NO USERNAME')
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

@login_required(login_url='/accounts/login/')
def edit_profile(request):
    if request.method == 'POST':
        print('3')
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.userprofile, files=request.FILES)
        if profile_form.is_valid():
            print('1')
            if user_form.is_valid():
                print('4')
                #print(profile_form)
                user_form.save()
                profile_form.save()
                return HttpResponseRedirect(reverse("accounts:edit_profile"))
            else:
                print('6')
        else:
            print('5')
    else:
        print('2')
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.userprofile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'accounts/edit_profile.html', context)




@login_required(login_url='/accounts/login/')
def view_model(request,pk=None):
    if pk:
        user = user.UserProfile.objects.get(pk=pk)
    else:
        user = request.user.UserProfile
    args = {'user': user}
    return render(request, 'accounts/profile_model.html', args)

# def edit_profile(request):
#   if request.method == 'POST':
#       form = EditProfileForm(request.POST, instance=request.user)

#       if form.is_valid():
#           form.save()
#           return redirect(reverse('accounts:profile'))
#   else:
#       form = EditProfileForm(instance = request.user)
#       args = {'form': form}
#       return render(request, 'accounts/edit_profile.html', args)









@login_required(login_url='/accounts/login/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect(reverse('accounts:profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user = request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

@login_required(login_url='/accounts/login/')
def model(request):
    if request.method == 'POST':
        form = modelform(data = request.POST , instance = request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))
        else:
            return redirect(reverse('accounts:model'))
    else:
        form = modelform(instance = request.user)
        args = {'form' : form}
        return render(request , 'accounts/model.html',args)















    # return render(request, 'accounts/model.html', {'form':form})

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            UserProfile.objects.get_or_create(user=new_user)
            return redirect(reverse('accounts:login1'))
    else:
        form = RegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/reg_form.html', context)


# def register(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.is_active = False
#             user.save()
#             current_site = get_current_site(request)
#             mail_subject = 'Activate your blog account.'
#             message = render_to_string('accounts/acc_active_email.html', {
#                 'user': user,
#                 'domain': current_site.domain,
#                 'uid':urlsafe_base64_encode(force_bytes(user.pk)),
#                 'token':account_activation_token.make_token(user),
#             })
#             to_email = form.cleaned_data.get('email')
#             email = EmailMessage(
#                         mail_subject, message, to=[to_email]
#             )
#             email.send()
#             return HttpResponse('Please confirm your email address to complete the registration')
#     else:
#         form = RegistrationForm()
#     return render(request, 'accounts/reg_form.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


# class HomeView(TemplateView):
#     template_name = 'home/home.html'

#     def get(self, request):
#         post_list = None
#         form = HomeForm(self.request.GET or None)
#         form1 = CommentForm(self.request.GET or None)
#         posts = Post.objects.filter(user = request.user).order_by('-created')
#         comments = Comment.objects.all()
#         users = User.objects.exclude(id=request.user.id)
#         query = request.GET.get('q')    
#         if query:
#                 posts = Post.objects.filter(

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/base_site.html
{% extends 'base.html' %}
{%  load static %}
{%block branding%}
<h1>
	admin</h1>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>HOME</h1>
{% block head %}
<title>home</title>
{% endblock %}

{% block body %}
<div class ="container">
	<h1>HOME</h1>
	</div>
{% endblock %}

accounts/templates/accounts/land.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Allabouthairdressers</title>

    <link href="{% static 'css/bootstrap.css' %}"  rel="stylesheet">
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Courgette|Kaushan+Script" rel="stylesheet">


  </head>

  <body>
    <nav class="navbar  bg-light static-top " style="height: 80px;">  
      <a class="navbar-brand" href="#"><img src="{% static 'accounts/logo1.png' %}"></a>

      <div class="button_main">
        
        <a class="btn btn_main" href="{% url 'accounts:register' %}"> Sign In</a>
        <a class="btn  btn_main2" data-toggle="modal" data-target="#login-modal"  href="{% url 'accounts:login1' %}"> Login</a>
        
        
      </div>
    </nav>

 <div class="main_container">
      <div class="overlay text-white text-center">
        <div class="container">     
            <div class="content">
              <h3>Beauty Specialist</h3>
              <p>Book hair and makeup professionals near to you</p>
            </div>
               <div class="col-md-12">
              <div class="row">
            <div class="select col-md-4" style="float: right;">
              <select>
                <option>All</option>
                <option>Gudimalkapur</option>
                <option>Jubliehills</option>
                <option>Madhapur</option>
                <option>SR Nagar</option>
                <option>Banjarahills</option>
                <option>Mahadevpuram</option>
              </select>
          </div>
            <div class="select_2 col-md-4">
              <select>
                <option>Select a service</option>
                <option>Gudimalkapur</option>
                <option>Jubliehills</option>
                <option>Madhapur</option>
                <option>SR Nagar</option>
                <option>Banjarahills</option>
                <option>Mahadevpuram</option>
              </select>
            </div>
              <div class="col-md-4 bttn_find">
                  <button type="submit" class="btn  btn-lg " >Find stylist</button>                
          </div>
          </div>
        </div>
      </div>
    </div>

 
<div class="content_main">
  <h1>How it works ?</h1>
      <div class=" cont_1">
        <div class="row">
          <div class="col-lg-3">
            <img src= "{% static 'accounts/location.jpg' %}" class="img-responsive"/>
          </div>
          <div class="col-md-9">
            <p>Choose your location, service and click on find stylist to get a list of stylists.</p>
          </div>
        </div>
      </div>
      <br>
      <div class=" cont_2">
        <div class="row">
          <div class="col-md-9">
            <p>Browse the list of profiles and choose the stylist depending upon his work, reviews from the users</p>
          </div>
          <div class="col-lg-3">
            <img src="{% static 'accounts/profile.png' %}" class="img-responsive">
          </div>
        </div>
      </div>
  </div>
  <br>
  <br>


  <div class="overlay_2 text-white text-center">
    <div class="container">
      <div class="content">
              <h3>Product Reviews</h3>
              <p>Get the best product reviews from the beauty professionals and models</p>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="text col-md-8">
          <input type="text" class="form-control" placeholder="Product name....." >
          </div>
          <div class="col-md-4 bttn_find_2" style="float: right;">
                  <button type="submit" class="btn  btn-lg " >Search</button>                
          </div>
        </div>
      </div>
    </div>
  </div>
<br>
<div class="content">
  <p>Find the best product reviews from the beauty professionals and models</p>
</div>


</div> 






<footer class="fot_1 bg-dark col-lg-12">
          <div class="row">
          <div class="on_1 col-md-6">
            <h3>All rights reserved</h3>
            <p style="text-align: left; font-size: 22px;">Our website is the online destination for beauty & wellness professionals and clients. Professionals can showcase their work, connect with new and existing clients, and build their business. Clients can discover new services and providers, book appointments online, and get inspired.</p>
          </div>
          <div class="col-md-3">
            <ul class=" navbar-nav">
              <h3>Media</h3>
               <li class="nav-item text-secondary">Our blog</li>
               <li class="nav-item text-secondary">Press</li>
               <li class="nav-item text-secondary">Stories</li>
               <li class="nav-item text-secondary">Videos</li>
              </ul>
              <ul class="navbar-nav">
              <h3>Talk To Us</h3>
               <li class="nav-item text-secondary">info@allabouthairdressers.com</li>
               <li class="nav-item text-secondary">Help Center</li>
              </ul>
              </div>
              <div class="col-md-3">
                <ul class="navbar-nav">
                  <li class="nav-item text-secondary">FIND PROFESSIONALS</li>
                  <li class="nav-item text-secondary">GET LISTED</li>
                  <li class="nav-item text-secondary">TEAM</li>
                  <li class="nav-item text-secondary">CAREERS</li>
                  <li class="nav-item text-secondary">TERMS FOR PROS</li>
                  <li class="nav-item text-secondary">TERMS FOR CLIENTS</li>
                  <li class="nav-item text-secondary">PRIVACY</li>
                  <li class="nav-item text-secondary">SITEMAP</li>
                </ul>
            </div>
        </footer>

  </body>
</html>

accounts/templates/accounts/login.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">

  <head> 

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Allabouthairdressers</title>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/landing-page.css' %}"  rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Courgette|Kaushan+Script" rel="stylesheet">


  </head>

  <body>
    <nav class="navbar  bg-light static-top " style="height: 80px;">  
      <a class="navbar-brand" href="#"><img src="{% static 'accounts/logo1.png' %}"></a>

      <div class="button_main">
         <!-- <a class="btn btn_main" href="index.html"> Home</a> -->
        <a class="btn btn_main" href="{% url 'accounts:register' %}"> Sign In</a>
        <a class="btn  btn_main2" data-toggle="modal" data-target="#login-modal" href="{% url 'accounts:login1' %}"> Login</a>
        
        
      </div>
    </nav>




        <div class="loginmodal-container">
          <h1>Login to Your Account</h1><br>
          <form action="" method="post">
          	{% csrf_token %}
          <input type="text" name="user" placeholder="Username">
          <input type="password" name="password" placeholder="Password">
          {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close"  data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}
          <input type="submit" name="login" class="login loginmodal-submit" value="Login">
          </form>
          
          <div class="login-help">
          <a href="#">Register</a> - <a href="#">Forgot Password</a>
          </div>
        </div>
  </body>
</html>

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load static  %}
{% block head %}

</script>
<title>logout</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
<h1>LOGGED OUT</h1>
<P>You Have Logged Out</P>
</div>

{% endblock %}

accounts/templates/accounts/model.html
{% extends 'base.html' %}
{%  load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
<title>EDIT</title>
{% endblock %}

{% block body %}
<div class="container">
<h1>EDIT</h1>
<form method="POST">
{% csrf_token %}
{{ form.as_p}}
<br>
<button type="submit">SUBMIT</button>
	
	
</form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{%  load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
<title>PROFILE</title>
{% endblock %}

{% block body %}
<div class="container">
<h1>Profile</h1>
<p>
	username:{{user}}<br>
	first name:{{user.first_name}}<br>
	last name:{{user.last_name}}<br>
	email:{{user.email}}<br>
	USER :{{ request.user.userprofile}}<br>
	DESCRIPTION :{{ request.user.userprofile.description}}<br>
	WEBSITE :{{ request.user.userprofile.website}}<br>	
	phome :{{ request.user.userprofile.phone}}<br>
	<img src="{{ request.user.userprofile.image.url }}" width="240">
</p>
</div>
{% endblock %}

accounts/templates/accounts/reg_form.html
 {% load static %}
 <!DOCTYPE html>
<html lang="en">

  <head> 

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Allabouthairdressers</title>

    <link href="{% static 'css/bootstrap.css' %}"  rel="stylesheet">
    <link href="{% static 'css/signup.css' %}"  rel="stylesheet">

    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Courgette|Kaushan+Script" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar  bg-light static-top " style="height: 80px;">  
      <a class="navbar-brand" href="#"><img src="{% static 'accounts/logo1.png' %}"></a>
      <div class="button_main">
        <a class="btn btn_main" href="{% url 'accounts:register' %}"> Sign In</a>
        <a class="btn  btn_main2" href="{% url 'accounts:login1' %}"> Login</a>
        
        
      </div>
    </nav>



<form action="" method="post">
            {% csrf_token %}
  <div class="container">
    <h1>Sign Up</h1>
    <hr>
     {% for field in form %}
      
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          <br>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      
    {% endfor %}
    

    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

    <div class="boo clearfix">
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>



  </body>
</html>

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}